name: Docker Metadata Testing

on: push 

jobs:
  steps-outcome:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare image metadata
        uses: docker/metadata-action@master
        id: meta
        with:
          images: dummy

      - name: steps.extra.outputs.json
        run: |
          echo ${{ fromJSON(steps.extra.outputs.json)['org.opencontainers.image.created'] }}
          echo ${{ fromJSON(steps.extra.outputs.json)['org.opencontainers.image.version'] }}
          echo ${{ fromJSON(steps.extra.outputs.json)['org.opencontainers.image.revision'] }}
