name: Docker Metadata Testing

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  steps-outcome:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: dummy
          tags: |
            type=sha,enable=true,priority=1000,prefix=,suffix=,format=short
            type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

      - name: steps.meta.outputs.json
        run: |
          echo ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          echo ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          echo ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          echo ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          echo ${{ steps.meta.outputs.json }}
          echo ${{ steps.meta.outputs.tag-names }}
