name: Docker Metadata Testing

on: push 

jobs:
  steps-outcome:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare image metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: dummy

      - name: Extract meta labels map
        id: extra
        run: echo ::set-output name=labels::$(jq -r -c '.target."docker-metadata-action".labels' ${{ steps.meta.outputs.bake-file }})

      - name: steps.extra.outputs.labels
        run: |
          echo ${{ fromJSON(steps.extra.outputs.labels)['org.opencontainers.image.created'] }}
          echo ${{ fromJSON(steps.extra.outputs.labels)['org.opencontainers.image.version'] }}
          echo ${{ fromJSON(steps.extra.outputs.labels)['org.opencontainers.image.revision'] }}
