name: Docker Metadata Testing

on: push 

jobs:
  steps-outcome:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare image metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: dummy

      - name: Extract meta labels map
        id: extra
        run: echo ::set-output name=labels::toJSON(fromJSON($(cat ${{ steps.meta.outputs.bake-file }} )).target.docker-metadata-action.labels)

      - name: steps.extra.outputs.labels
        run: |
          echo ${{ steps.extra.outputs.labels['org.opencontainers.image.created'] }}
          echo ${{ steps.extra.outputs.labels['org.opencontainers.image.version'] }}
          echo ${{ steps.extra.outputs.labels['org.opencontainers.image.revision'] }}
