name: Docker Metadata Testing

on: push 

jobs:
  steps-outcome:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare image metadata
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: dummy
        run: echo ::set-output name=labels-map::fromJSON(toJSON($(cat ${{ steps.meta.outputs.bake-file }} )).target.docker-metadata-action.labels)

      - name: steps.meta.outputs.labels-map
        run: |
          echo ${{ steps.meta.outputs.labels-map['org.opencontainers.image.created'] }}
          echo ${{ steps.meta.outputs.labels-map['org.opencontainers.image.version'] }}
          echo ${{ steps.meta.outputs.labels-map['org.opencontainers.image.revision'] }}
